### ISSUE TITLE
React auto suggest component disappears when a long loop is encountered

### ISSUE THREAD

**Issue by i-like-robots** [Financial-Times/treecreeper#240]
**Describe the bug**

There have been reports of the autosuggest component disappearing when users interact with it, e.g. https://financialtimes.slack.com/archives/C07B3043U/p1589192998306200

Opening the browser console the following error is found emanating from the component: https://reactjs.org/docs/error-decoder.html/?invariant=185

This bug is not seen consistently which may indicate a race condition or other variability.

**To Reproduce**

1. Go to edit the record for a person 
2. Scroll down to the "individual roles" section
2. Highlight the "GDPR Data owner for systems" field
3. Add systems

**Expected behavior**

After selecting a system the input field should be cleared and the system displayed below.

**Screenshots**

<img width="1020" alt="Screenshot 2020-05-11 at 12 27 27" src="https://user-images.githubusercontent.com/271645/81556789-d06c2000-9382-11ea-8b1d-532b37b56a40.png">

**Desktop (please complete the following information):**

-   OS: MacOS
-   Browser Firefox
-   Version 76

**Additional context**

The `react-autosuggest` component states that it is unmaintained but it has had recent releases. However, the error appears to be from our own integration code.

**Comment by i-like-robots** [comment]
As indicated by the React error message, the loop occurs between  the`componentDidUpdate()` lifecycle method inside the `react-autosuggest` component and the `onSuggestionHighlighted()` callback inside the relationship picker which sets some state.

It is quite easy to recreate by typing a search term quickly then immediately pressing down to highlight a suggestion. 

From digging a little deeper I suspect the issue is caused by the `fetchSuggestions()` method not being throttled or prevented from setting a stale state. Because of the suggestions state can be updated multiple times in rapid succession and trigger `componentDidUpdate()` and  `onSuggestionHighlighted()` as well, therefore reaching the maximum queue depth.

I suggest this could be fixed by updating the `fetchSuggestions()` method to avoid making multiple concurrent requests.

**Comment by i-like-robots** [comment]
Unfortunately this issue is still present:
 
<img width="976" alt="Screenshot 2020-05-15 at 09 42 17" src="https://user-images.githubusercontent.com/271645/82030512-76c06a00-9690-11ea-8808-15322557ab86.png">

**Comment by i-like-robots** [comment]
Console based development (because the React devtools could not keep up) but this clearly shows where the loop happens:

<img width="1254" alt="Screenshot 2020-05-15 at 12 20 13" src="https://user-images.githubusercontent.com/271645/82045164-877bda80-96a6-11ea-88f3-46d6a2a6210e.png">

I have tried updating to the latest version of `react-autosuggest` but this does appear to be within our own code.

**Comment by i-like-robots** [comment]
The screenshot below shows the CPU profile when interacting with the relationship picker: 

<img width="894" alt="Screenshot 2020-05-15 at 12 50 24" src="https://user-images.githubusercontent.com/271645/82047445-bf851c80-96aa-11ea-8b3d-5e881976dc46.png">

**Comment by wheresrhys** [comment]
Can this be closed now @i-like-robots
