### ISSUE TITLE
Markdown formatting v yaml multi-line descriptions

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/treecreeper#245]
**Describe the bug**
The formatting of multi-line Biz Ops schema description fields as markdown triggers the addition of extra blank lines; single line descriptions are fine.

**To Reproduce**
1) You need to be running treecreeper v0.5.10
2) Goto System/single-system-view/edit?#ownership-&-knowledge
3) Note the new line between `the` and `Group` within the description for `Delivered By Team`
4) Goto System/single-system-view/edit?#service-operability-review
5) Note how the `SOS traffic light` description is one nicely wrapped line of text.

**Expected behavior**
All field descriptions should appear as one nicely wrapped line unless they contain lines which whose markdown forces them on to new lines (such as the hyphen bullet point)

**Screenshots**
![image](https://user-images.githubusercontent.com/11228420/82027807-b5542580-968c-11ea-9e11-58f7ec5e3fb2.png)

![image](https://user-images.githubusercontent.com/11228420/82027853-c6049b80-968c-11ea-9643-cd2c60fdf7bd.png)

**Desktop (please complete the following information):**

-   OS: Windows
-   Browser: chrome
-   Version: 80

**Additional context**
The problem only occurs with treecreeper v0.5.10 since that version introduced descriptions with markdown formatting
v.0.5.10 is live in NPM but not built into any live apps at present.

**Comment by GeoffThorpeFT** [comment]
We may need to balance the convenience of writing long descriptions as multi-line yaml with our wish to explicitly format some of those longer descriptions across multiple lines.
e.g. Where we just want to provide unformatted text we should use single line yaml for the description and let markdown/html split the line during rendering. However, when we want bullet points and bold we should use multiline yaml to ensure the markdown control characters are at the beginning of the lines.

**Comment by GeoffThorpeFT** [comment]
We could also consider that this issue is caused by us writing multi-line yaml whose individual lines are too long (any therefore wrap triggering an unexpected new line).  In other words we could write a test to trigger failure when any line of a multi-line exceeds 80 characters.  Single line yaml can be as long as you want since they will wrap nicely.

**Comment by GeoffThorpeFT** [comment]
After further investigation I note we are using both the `|` and `>` style of yaml to indicate multi-line text. The former introduced linefeeds while the later does not.  Ideally we would only use` |` for markdown where the linefeeds we necessary to force the correct positioning of bulltet points.

**Comment by GeoffThorpeFT** [comment]
Partially resolved by schema updates.

**Comment by GeoffThorpeFT** [comment]
Future issues with the formatting require detection via https://github.com/Financial-Times/treecreeper/pull/247

**Comment by wheresrhys** [comment]
I think making it any better than this is impossible as we simply cannot detect whether the user intends teh linebreaks to be meaningful or not
