### ISSUE TITLE
Default inactiveRule

### ISSUE THREAD

**Issue by lucas42** [Financial-Times/treecreeper#282]
**Is your feature request related to a problem? Please describe.**
At the moment, if a consumer wants to work which items are active or inactive, it needs to:
1. Look for `inactiveRule` field on the type.  If it's present, apply the rule to each item
2. Look for an `isActive` field on the type.  If it's present, check the value of this field for each item
3. For types without either of these fields, treat all items as active.

See the [autocomplete demo](https://github.com/Financial-Times/treecreeper/blob/f7a57fe461fc57733a224ad88614fd1b647c935a/demo/controllers/autocomplete.js#L22) for an example implementation.

**Describe the solution you'd like**
I'd like this logic to live in a single place so it doesn't need recreating in multiple consumers.

**Describe alternatives you've considered**
I've tried recreating the logic in places which need it, eg https://github.com/Financial-Times/biz-ops-admin/pull/417

**Comment by wheresrhys** [comment]
Replacing with https://github.com/Financial-Times/biz-ops-api/issues/581
