### ISSUE TITLE
Surface an activeRule

### ISSUE THREAD

**Issue by lucas42** [Financial-Times/treecreeper#283]
**Is your feature request related to a problem? Please describe.**
At the moment, types with custom rules around which items are active or inactive do so using the `inactiveRule` field.  This means if a consumer wants to know which items are active, they have to apply some custom logic to try to invert the rule.  (Or query everything and then do a diff against the list of inactive items)

**Describe the solution you'd like**
I'd like to be able to get a rule for a given type to know which items are active, without needing to do any inversion logic in the consumer.

**Describe alternatives you've considered**
Writing some [inversion logic](https://github.com/Financial-Times/biz-ops-admin/blob/c2aa2d2d2d1c60212a6af526fabaf0a03d7dfd9e/src/listHandler.js#L71-L84) in the consumer.

**Additional context**
Ideally this would work seemlessly with #282

**Comment by lucas42** [comment]
It'd be good if, as part of this, we could abstract away the idiosyncrasies around how graphql `_not` filters deal with null values.

**Comment by wheresrhys** [comment]
replacing with https://github.com/Financial-Times/biz-ops-api/issues/581
