### ISSUE TITLE
Document the need to avoid $ in neo4j db password

### ISSUE THREAD

**Issue by GeoffThorpeFT** [Financial-Times/treecreeper#333]
When `$` is placed in a neo4j db password the Heroku instances of Biz Ops API (TEST and PROD) will send the correct NEO4J_BOLT_PASSWORD to treecreeper via Heroku.

However, local runs use make's `include` command which has a bug with symbol substitution which forces the `$` to be treated as a special character and removed.

Document the need to avoid using `$` (and potentially some other special characters) in the password in the readme/runbook to highlight the issue to anyone rotating passwords or troubleshooting database access failures.

**Comment by wheresrhys** [comment]
duplicate
