### ISSUE TITLE
Regex Matching for Bizops Schema Changes is Broken

### ISSUE THREAD

**Issue by bibbycodes** [Financial-Times/treecreeper#362]
**Describe the bug**
When adding `changePermission` locks for the `DNSZone` in the bizops Schema I encountered an issue:

```bash
errors: [
    {
      params: { pattern: '^[a-z][\\-a-z]+[a-z]$' },
      message: 'should match pattern "^[a-z][\\-a-z]+[a-z]$"',
      signpost: 'Problem in `0` of the `createPermissions` section of the `DNSZone` type'
    },
```

When matching for:

```yaml
createPermissions:
  - biz-ops-route53-importer
```

**To Reproduce**

1. Go to `biz-ops-schema` repo
2. Add `createPermissions` in the `schema/types/DNSZone.yaml`
3. Push up changes
4. Observe the error

**Expected behavior**

Pushing this change up should not cause this error. The system code `biz-ops-route53-importer` should be considered valid

**Solution**

Change the regex matching to be `^[a-z][\\a-z0-9-]+[a-z]$`

**Comment by wheresrhys** [comment]
Yep this fix looks basically correct, although 2 tweaks:
- important that the `\\` remains before the `-`; this gets converted to `\-` i.e. matches `-`
- the final `[a-z]` statement should also include `0-9` - while system codes starting with numbers is out, it's fine for them to end with a number

**Comment by bibbycodes** [comment]
Made a PR => https://github.com/Financial-Times/treecreeper/pull/363
